# Generated by Django 5.0b1 on 2023-11-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_band'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'venue')},
        ),
    ]
